### ISSUE TITLE
[BUG] isHex() verification rule problem

### ISSUE THREAD

**Issue by loktarjugg** [web3p/ethereum-tx#17]
test address: 0x3db20a82Cf2C02642A8c2E163063640F4Effe59F

when I have capital letters in my address, validation fails

**Comment by sc0Vu** [comment]
Hi @loktarjugg, which version did you use?

If you're use latest version,  it might be issue in ethereum-util, and I'll try to reproduce the problem and fix this.

**Comment by loktarjugg** [comment]
@sc0Vu thank you for your reply
my version is :
"web3p/ethereum-tx": "^0.3.3"

**Comment by sc0Vu** [comment]
Hi @loktarjugg, thanks for your report,  this issue had been fixed and we published a new version of ethereum-util.
See: https://github.com/web3p/ethereum-util/commit/ed00c4dd5df79864d25a691aaefd6728d7f42796
