### ISSUE TITLE
tx hash isn't same

### ISSUE THREAD

**Issue by chenyunecjtu** [web3p/ethereum-tx#20]
{"from":"0x17b96334442d2eb8bdf4be769f67d38b5e094a90","to":"0xbe45e9ce05a049c6e6bf00e523f2b2d76b11f771","data":"0x","nonce":"0x27","gasPrice":"0x2540be400","value":"0xe8d4a51000","gas":"0x5210","chainId":20180511}  

eth_sendRawTransaction get hash:0x8df7c38e9d6c1052c81f79adfb3777f9402f817a69fe6ae0517c356f9516f4a1 

Transaction->hash is 0x977faa0fbc7f783c709cd39da8562e9ac7bc142f33afcbde3dd21a17abda797b

**Comment by sc0Vu** [comment]
@chenyunecjtu did you mean `Transaction->hash(false)` was not equal `eth_sendRawTransaction` hash?
Because `Transaction->hash(false)` is hashing rlp encoded transaction data.
