### ISSUE TITLE
Tx Data is always null 

### ISSUE THREAD

**Issue by danirabbani90** [web3p/ethereum-tx#23]
hi there i have just followed the steps you wrote for sending ethereum transaction but unfortunately in the log the ethereum txdata is always null that is why it is unable to sign transactions ?

**Comment by sc0Vu** [comment]
Hi @danirabbani90, would you like to post code here (please do not include sensitive information)?

**Comment by huigan** [comment]
你好，我签名后向公共节点（https://ethereum.api.nodesmith.io/v1/mainnet/jsonrpc）发起请求，可以返回交易hash，但是这个交易hash用eth_getTransactionByHash查到的信息中blockHash和blockNumber都是null，我用eth_getTransactionCount获取最新交易数，并修改了nonce，但还是这样，我的操作有哪里不对的吗？谢谢了
```
$transaction = new Transaction([
            'nonce' => '0xd',
            'from' => "0xF728f02b81DfE880A6CD8748893c94925d70a8B6",
            'to' => '0x68484CF447d6E2eA8AF27d2b1DfE9b8DC5d24DB3',
            'gas' => '0x1',
            'gasPrice' => '0xee6b2800',
            'value' => '0x38d7ea4c68000',
            'chainId' => 1
        ]);

        $serialize=$transaction->serialize();
        $signedTransaction = $transaction->sign("PrivateKey");
        $getFromAddress=$transaction->getFromAddress();

        $web3 = new Web3(JSONRPC_HOST);
        $eth=$web3->eth;
        $eth->sendRawTransaction('0x'.$signedTransaction, function ($err, $transaction) use ($eth) {
            if ($err !== null) {
                echo 'Error: ' . $err->getMessage();
                return;
            }
            echo 'Tx hash: ' . $transaction . PHP_EOL;
            $eth->getTransactionByHash($transaction, function ($err, $res) use ($eth) {
                if ($err !== null) {
                    var_dump($err->getMessage());
                    return;
                }
                dump($res);
                //0xcff87fe6c618a7cce954701c954a9c701d981f3b1bcab6c9e931b7fc159a9afa
            });
            //0xcff87fe6c618a7cce954701c954a9c701d981f3b1bcab6c9e931b7fc159a9afa
        });
```

**Comment by huigan** [comment]
> 你好，我签名后向公共节点（[https://ethereum.api.nodesmith.io/v1/mainnet/jsonrpc）发起请求，可以返回交易hash，但是这个交易hash用eth_getTransactionByHash查到的信息中blockHash和blockNumber都是null，我用eth_getTransactionCount获取最新交易数，并修改了nonce，但还是这样，我的操作有哪里不对的吗？谢谢了](https://ethereum.api.nodesmith.io/v1/mainnet/jsonrpc%EF%BC%89%E5%8F%91%E8%B5%B7%E8%AF%B7%E6%B1%82%EF%BC%8C%E5%8F%AF%E4%BB%A5%E8%BF%94%E5%9B%9E%E4%BA%A4%E6%98%93hash%EF%BC%8C%E4%BD%86%E6%98%AF%E8%BF%99%E4%B8%AA%E4%BA%A4%E6%98%93hash%E7%94%A8eth_getTransactionByHash%E6%9F%A5%E5%88%B0%E7%9A%84%E4%BF%A1%E6%81%AF%E4%B8%ADblockHash%E5%92%8CblockNumber%E9%83%BD%E6%98%AFnull%EF%BC%8C%E6%88%91%E7%94%A8eth_getTransactionCount%E8%8E%B7%E5%8F%96%E6%9C%80%E6%96%B0%E4%BA%A4%E6%98%93%E6%95%B0%EF%BC%8C%E5%B9%B6%E4%BF%AE%E6%94%B9%E4%BA%86nonce%EF%BC%8C%E4%BD%86%E8%BF%98%E6%98%AF%E8%BF%99%E6%A0%B7%EF%BC%8C%E6%88%91%E7%9A%84%E6%93%8D%E4%BD%9C%E6%9C%89%E5%93%AA%E9%87%8C%E4%B8%8D%E5%AF%B9%E7%9A%84%E5%90%97%EF%BC%9F%E8%B0%A2%E8%B0%A2%E4%BA%86)
> 
> ```
> $transaction = new Transaction([
>             'nonce' => '0xd',
>             'from' => "0xF728f02b81DfE880A6CD8748893c94925d70a8B6",
>             'to' => '0x68484CF447d6E2eA8AF27d2b1DfE9b8DC5d24DB3',
>             'gas' => '0x1',
>             'gasPrice' => '0xee6b2800',
>             'value' => '0x38d7ea4c68000',
>             'chainId' => 1
>         ]);
> 
>         $serialize=$transaction->serialize();
>         $signedTransaction = $transaction->sign("PrivateKey");
>         $getFromAddress=$transaction->getFromAddress();
> 
>         $web3 = new Web3(JSONRPC_HOST);
>         $eth=$web3->eth;
>         $eth->sendRawTransaction('0x'.$signedTransaction, function ($err, $transaction) use ($eth) {
>             if ($err !== null) {
>                 echo 'Error: ' . $err->getMessage();
>                 return;
>             }
>             echo 'Tx hash: ' . $transaction . PHP_EOL;
>             $eth->getTransactionByHash($transaction, function ($err, $res) use ($eth) {
>                 if ($err !== null) {
>                     var_dump($err->getMessage());
>                     return;
>                 }
>                 dump($res);
>                 //0xcff87fe6c618a7cce954701c954a9c701d981f3b1bcab6c9e931b7fc159a9afa
>             });
>             //0xcff87fe6c618a7cce954701c954a9c701d981f3b1bcab6c9e931b7fc159a9afa
>         });
> ```


换了一个公共节点，就可以了，之前用的nodesmith.io，改成infura.io的就可以了

**Comment by sc0Vu** [comment]
@huigan because your transaction wasn't included in the block, you got the null when search the transaction hash. You might need to check the gas or gasPrice.
