### ISSUE TITLE
Error while installing

### ISSUE THREAD

**Issue by nagarjunbn** [web3p/ethereum-tx#24]
$ composer require web3p/ethereum-tx
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Can only install one of: simplito/elliptic-php[1.0.4, 1.0.3].
    - Can only install one of: simplito/elliptic-php[1.0.3, 1.0.4].
    - Can only install one of: simplito/elliptic-php[1.0.3, 1.0.4].
    - web3p/ethereum-tx 0.3.4 requires simplito/elliptic-php 1.0.3 -> satisfiable by simplito/elliptic-php[1.0.3].
    - Installation request for web3p/ethereum-tx ^0.3.4 -> satisfiable by web3p/ethereum-tx[0.3.4].
    - Installation request for simplito/elliptic-php (locked at 1.0.4) -> satisfiable by simplito/elliptic-php[1.0.4].

Installation failed, reverting ./composer.json to its original content.

**Comment by sc0Vu** [comment]
@nagarjunbn Thanks for your report, I'll check this.
