### ISSUE TITLE
It doesn't work now, some corrections needed

### ISSUE THREAD

**Issue by mr-older** [web3p/ethereum-tx#26]
You need to add check for nullable $tx in __construct where $this->txData = $tx.

I.e.:
> 	if(!empty($tx))
> 	{
> 		$this->txData = $tx;
> 	}

**Comment by sc0Vu** [comment]
Since the `$tx` is empty array (see: https://github.com/web3p/ethereum-tx/blob/master/src/Transaction.php#L144)

and we do check whether input is hex encoded string.

I don't figure out why we should check nullable `$tx` in __construct.

**Comment by mr-older** [comment]
If you are passing array, not hexstring, here: [https://github.com/web3p/ethereum-tx/blob/master/src/Transaction.php#L176](url), your $tx variable doesn't exists after IFs. Your code is not working in that case at all, failing with assignment to nothing. There are numerous methods to solve it, including involving more experienced programmers, of course. Just no-testing-error :)

**Comment by sc0Vu** [comment]
Oh, I see! I didn't set the default value of $txData.
Good finding, Thanks @mr-older !
