### ISSUE TITLE
private key should be non-hexed

### ISSUE THREAD

**Issue by sarlongda** [web3p/ethereum-tx#28]
When I use sign function you said the private key should be hexed private key with zero prefixed.
But If I input "0x....." private key, then this returns an error

**Comment by sc0Vu** [comment]
@sarlongda 

Is this issue related to #27?

**Comment by sc0Vu** [comment]
That's weird, the 0x prefixed test passed.

After read through elliptic source code, I think the le mode can break 0x prefixed private.

I'm going to remove the 0x before generate private key.

**Comment by newtmex** [comment]
I got this error:  ```The input type didn't support.  at vendor/web3p/rlp/src/RLP.php:223  ...```
