### ISSUE TITLE
Error: transaction could not be decoded: could not recover secp256k1 key: calculated Rx is larger than curve P

### ISSUE THREAD

**Issue by Djdriver** [web3p/ethereum-tx#32]
Sorry for bringing up the same issue again. I'm trying to send a signed raw transaction to Rinkeby testnet but it always throws me this error. I've checked the signed tx hash with the same data in web3py and it gives me the same hashes. I've also checked them with web3js and I get the same hashes too and I can sign and send the transaction with both libraries without any problems, but I'm facing issues when I'm trying to do the same in web3php.

My private key is hexed and 32 byte-length. I don't know where is the problem right now. This is the transaction code a bit simplified:

        $contract = new Contract('http://infura node url/', $contractABI);

        $param1 = 40;
        
        $nombreFuncion = 'functionName';

        $data = '0x' . $contract->at($contractAddress)->getData($nombreFuncion, $param1, $param2);

        $nonce = 0;
        $eth->getTransactionCount($acc, function($err, $num) use (&$nonce) {
            if ($err != null) {
                echo 'Error: ' . $err->getMessage() . PHP_EOL;
                return;
            }
            $nonce = $num;
        });
        $nonceHex = '0x' . dechex(intval($nonce->toString()+1));

        $args_tx = [
            'nonce' => $nonceHex,
            'from' => $acc1,
            'to' => $contractAddress,
            'gas' => '0x' . dechex(100000),
            'gasPrice' => '0x' . dechex(100),
            'data' => $data
        ];

        $tx = new Transaction($args_tx);

        $tx_signed = $tx->sign($privateKey);

        $eth->sendRawTransaction($tx_signed, function($err, $txHash) {
            if($err !== null) {
               echo 'Error: ' . $err->getMessage() . PHP_EOL;
                return;
            }
            echo 'txHash: ' . $txHash . PHP_EOL;
        });

signed tx hash (which is the same as the serialized one): 0xf8a52b64830186a0949b273326cAE66686945736a2569fFB2d2374EE1880b844f33113450000000000000000000000000000000000000000000000000000000000000028617273757300000000000000000000000000000000000000000000000000000024a059574774ccdca3027ae8c874dd8e196dbeca52c2d82a897357f542ae289235b8a062f88964a245bebae84aa4333c7952bb0b96d1d609e239b4bc2ddf4f3a1c06cf

Thanks in advance!

**Comment by Djdriver** [comment]
I'm going to close the issue. I resolved the issue, I needed to add the chainId of the Rinkeby testnet. Now I'm sending the transactions and it gives me a correct hash, but it doesn't appear on etherscan, but that's not a problem of the library. Thanks!

**Comment by Djdriver** [comment]
P.S. : doing $nonce + 1 the transaction doesn't arrive to blockchain, be careful with that.

**Comment by davidtmnolan** [comment]
@Djdriver 

> P.S. : doing $nonce + 1 the transaction doesn't arrive to blockchain, be careful with that.

What worked for you? What is the proper way to calculate the nonce value?

**Comment by Djdriver** [comment]
> @Djdriver
> 
> > P.S. : doing $nonce + 1 the transaction doesn't arrive to blockchain, be careful with that.
> 
> What worked for you? What is the proper way to calculate the nonce value?

First you need to add web3.utils:

`use Web3\Utils;`

And then, using the in-built functions of utils package I calculated a persistent nonce value every time I did a tx:

`        $nonceHex = '0x' . $utils->toHex($nonce);
`

Using the original way I posted at first it would do some TXs but not all TXs could arrive to Blockchain.
