### ISSUE TITLE
rlp: input string too long for uint64, decoding into (types.LegacyTx).Nonce.

### ISSUE THREAD

**Issue by miguilimzero** [web3p/ethereum-tx#39]
I'm currently trying to broadcast a raw ethereum classic transaction. However after the nonce 160, it stopped working and is now returning the following error: ``rlp: input string too long for uint64, decoding into (types.LegacyTx).Nonce.``.

```php
[
  "nonce" => "0xa0"
  "from" => "0x3e59426f0aeaf08946f9fa05a4df1d19440b4ec7"
  "to" => "0xd2de7e8f69a2493ef2269e78170268a18d9804d6"
  "gas" => "0x5208"
  "gasPrice" => "0x3b9aca00"
  "value" => "0x5af3107a4000"
  "chainId" => 61
  "data" => ""
]
```

**Comment by sc0Vu** [comment]
@srdante Thanks for reporting this issue, I'll look into this.

**Comment by sc0Vu** [comment]
There was a same issue: https://github.com/web3p/rlp/issues/21.
