### ISSUE TITLE
Reconsider EIP 155 transaction

### ISSUE THREAD

**Issue by sc0Vu** [web3p/ethereum-tx#4]
There is an issue on this library when sign transaction with chain id.

See issue: https://github.com/sc0Vu/web3.php/issues/56

I think we should reconsider EIP 155 transaction

https://github.com/ethereum/EIPs/blob/master/EIPS/eip-155.md

On ethereumjs-tx:
```
hash function

if (this._chainId > 0) {
  const raw = this.raw.slice()
  this.v = this._chainId
  this.r = 0
  this.s = 0
  items = this.raw
  this.raw = raw
} else {
  items = this.raw.slice(0, 6)
}

sign function

const msgHash = this.hash(false)
const sig = ethUtil.ecsign(msgHash, privateKey)
if (this._chainId > 0) {
  sig.v += this._chainId * 2 + 8
}
```

Another ethereum tx library: https://github.com/warren-bank/ethereumjs-tx-sign/blob/14aaa96f8b49e0bdced13d64161fbda3e2300a80/index.js#L91

**Comment by sc0Vu** [comment]
```
var recoveryParam = (kp.getY().isOdd() ? 1 : 0) |
                        (kpX.cmp(r) !== 0 ? 2 : 0);

// Use complement of `s`, if it is > `n / 2`
if (options.canonical && s.cmp(this.nh) > 0) {
  s = this.n.sub(s);
  recoveryParam ^= 1;
}
```

**Comment by jianhuihi** [comment]
sign without chainId  send transaction

Error: insufficient funds for gas * price + value

```
$v = 37;
        $chainId = $this->offsetGet('chainId');
        if ($chainId) {
            $v = (int) $chainId * 2 + 35;
        }
        $this->offsetSet('v', $v);
```



chainID = 1;  return the same result.

**Comment by olegabr** [comment]
any update on this?

**Comment by jianhuihi** [comment]
try this

https://github.com/Domraider/php-eth-raw-tx

**Comment by olegabr** [comment]
It has a lot of requirements to the server. hard to use it for average user. 
I want to use it for a WordPress plugin, so, user friendlyness is an important issue for me.
It is even easier to use geth with JSON-RPC in this case.
The pure PHP implementation is a must to make things really simple for such applications.

**Comment by sc0Vu** [comment]
I think the pure PHP implementation is good.
I'll fix this issue when secp256k1 recover function finished (https://github.com/web3p/secp256k1/issues/6).
Still working hard on that (this.g.mulAdd).

Update:
I found the full implement of elliptic: https://github.com/simplito/elliptic-php
Try this to sign and recover tonight.

**Comment by jianhuihi** [comment]
any update on this?

**Comment by jianhuihi** [comment]
https://github.com/jianhuihi/ethereum-tx

**Comment by sc0Vu** [comment]
Just release 0.3 that support EIP155 https://github.com/web3p/ethereum-tx/releases/tag/0.3

**Comment by olegabr** [comment]
Wow! Does it means that there is a pure PHP Ethereum tx library exists now? I'm excited! :-)
Will try it in my plugin shortly: https://wordpress.org/plugins/cryptocurrency-product-for-woocommerce/
