### ISSUE TITLE
BEP-20 transaction

### ISSUE THREAD

**Issue by array-drian** [web3p/ethereum-tx#40]
Hello,
so I am pretty new to this kind of coding and wanted to create a function to sent bnb transactions(0.1bnb gasprive 10gwei, gaslimit 21000). For now I am using the testnetwork and I just cant get it to work. Thanks in advance.

    use Web3\Web3;
    use Web3p\EthereumTx\Transaction;

    $web3 = new Web3('https://data-seed-prebsc-1-s1.binance.org:8545');
    $eth = $web3->eth;

    $transaction = new Transaction([
        'nonce' => '0x' . bin2hex(makeRandomString()),
        'from' => "0x73AdF374419E4BAaDDC243e2250d6f6661D0Ff46",
        'to' => "0x367A32ba87E10e3AdAE8C60546B9383c78a3841A",
        'gas' => '0x' . dechex(21000),
        'gasPrice' => '0x' . dechex(10000000000),
        'value' => '0x' . dechex(100000000),
        'chainId' => 97
    ]);

    $signedTransaction = $transaction->sign($privatekey);

    $eth->sendRawTransaction('0x'. $signedTransaction, function ($err, $tx) {
        if ($err !== null) {
            $err->getMessage();
        }
        echo 'TX: '. $tx . PHP_EOL;
    });

    function makeRandomString($bits = 256) {
        $bytes = ceil($bits / 8);
        $return = '';
        for ($i = 0; $i < $bytes; $i++) {
            $return .= chr(mt_rand(0, 255));
        }
        return $return;
    }`

**Comment by sc0Vu** [comment]
Hi Did it work?

**Comment by array-drian** [comment]
> Hi Did it work?

No and I really dont know what I am doing wrong

**Comment by Razorholt** [comment]
still no luck?

**Comment by tianheng2017** [comment]
> nonce

傻屌，nonce不能用随机数，用getTransactionCount获取

**Comment by tianheng2017** [comment]
> Hello, so I am pretty new to this kind of coding and wanted to create a function to sent bnb transactions(0.1bnb gasprive 10gwei, gaslimit 21000). For now I am using the testnetwork and I just cant get it to work. Thanks in advance.
> 
> ```
> use Web3\Web3;
> use Web3p\EthereumTx\Transaction;
> 
> $web3 = new Web3('https://data-seed-prebsc-1-s1.binance.org:8545');
> $eth = $web3->eth;
> 
> $transaction = new Transaction([
>     'nonce' => '0x' . bin2hex(makeRandomString()),
>     'from' => "0x73AdF374419E4BAaDDC243e2250d6f6661D0Ff46",
>     'to' => "0x367A32ba87E10e3AdAE8C60546B9383c78a3841A",
>     'gas' => '0x' . dechex(21000),
>     'gasPrice' => '0x' . dechex(10000000000),
>     'value' => '0x' . dechex(100000000),
>     'chainId' => 97
> ]);
> 
> $signedTransaction = $transaction->sign($privatekey);
> 
> $eth->sendRawTransaction('0x'. $signedTransaction, function ($err, $tx) {
>     if ($err !== null) {
>         $err->getMessage();
>     }
>     echo 'TX: '. $tx . PHP_EOL;
> });
> 
> function makeRandomString($bits = 256) {
>     $bytes = ceil($bits / 8);
>     $return = '';
>     for ($i = 0; $i < $bytes; $i++) {
>         $return .= chr(mt_rand(0, 255));
>     }
>     return $return;
> }`
> ```

傻屌，nonce不能用随机数，用getTransactionCount获取

**Comment by sc0Vu** [comment]
Hey @Razorholt, you have to fetch nonce from blockchain state with `getTransactionCount()`. In EVM based blockchain, it'll checkout the nonce in their state database.
