### ISSUE TITLE
Signing data differs from eip-155

### ISSUE THREAD

**Issue by zgos** [web3p/ethereum-tx#8]
While I try to inspect the internal of a signed tx, and according eip-155[https://github.com/ethereum/EIPs/blob/master/EIPS/eip-155.md], the signing data should be '0xec098504a817c800825208943535353535353535353535353535353535353535880de0b6b3a764000080018080', but in you testcase, it assert to '0xec098504a817c800825208943535353535353535353535353535353535353535880de0b6b3a764000080808080' a little differences from eip-155.

**Comment by zgos** [comment]
here is my example:
`  $transaction = new Transaction([
    'nonce' => '0x9',
    'to' => '0x3535353535353535353535353535353535353535',
    'gas' => '0x5208',
    'gasPrice' => '0x4a817c800',
    'value' => '0xde0b6b3a7640000',
    'chainId' => 1,
    'data' => ''
  ]);
  var_dump($transaction->serialize()->toString('hex'));`

**Comment by sc0Vu** [comment]
@zgos Because the default r, s, v in txData is NULL.
If you call serialize() directly, it won't change the r, s, v in txData.
You can fix this by set r, s, v:

```
$transaction['r'] = '';
$transaction['s'] = '';
$transaction['v'] = 1;
$signingData = $transaction->serialize()->toString('hex'); // equal: ec098504a817c800825208943535353535353535353535353535353535353535880de0b6b3a764000080018080
```

**Comment by zgos** [comment]
Thanks for your response.
I'm now using the recently code, it throw "invalid sender" exception, and in previously version, it complained "insufficient funds for gas * price + value" as many people issued. Can you have idea about this, thanks again for ths awesome code on ethereum.

**Comment by sc0Vu** [comment]
The chainId might be wrong.

**Comment by sc0Vu** [comment]
@zgos recently I try to send the signed transaction, it always return invalid signature.
After trace the signed r s v, I found that the signature was wrong (from elliptic-php).
And I try to sign with web3p/secp256k1, the signature was correct, still try to figure out the problem.

**Comment by olegabr** [comment]
Look at this please: #11 
There is a problem if value = 0.

**Comment by Stephan-MC** [comment]
I know it may be late but i'll leave my solution for any one who encounters the issue again.

I solve my own problem by ensuring the following
- Valid and matching ```address (sender)``` and ```private_key``` pair.
- Correct ```chain id``` i.e ```1337``` (NB: will fail if converted to hex).
